default: &default
  host: localhost
  adapter: postgresql
  username: dev
  password: dev
  pool: 5
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: 'mahmoney_development'

test:
  <<: *default
  database: mahmoney_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: 'mahmoney'